### ISSUE TITLE
Update widgets for Android 12/API 31

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#217]
- [x] handle rounded corners appropriately
- [x] support pinning (#218)
- [x] support dynamic previews
- [x] reduce non-xml layout twiddling
- [x] remove abbreviations in names 
- [x] support reconfiguration
- [x] default to a 'loading state' (See #53) rather than error state
- [x] use layout viewer across various dimensions, making sure we've fixed (#12) (#120)
- [x] check what happens when we add widgets when we're not signed in (#66)

See:
- #207

**Comment by adamwolf** [comment]
This has been released in Beedroid 5.
